### ISSUE TITLE
Could you help upgrade the vulnerble dependency in django-social-layer? 

### ISSUE THREAD

**Issue by MikeWazoWski123** [gsteixeira/django-social-layer#1]
Hi, @gsteixeira, I'd like to report a vulnerability issue in **django-social-layer_0.3.4**.
### Issue Description
I noticed that **django-social-layer_0.3.4** directly depends on **opencv-python_4.5.4.60**.
However, **opencv-python_4.5.4.60** sufferes from the vulnerabilites which the C libraries exposed as following dependency graph shows. Refer to [issue](https://github.com/opencv/opencv-python/issues/646).
### Dependency Graph between Python and Shared Libraries
![image](https://user-images.githubusercontent.com/102780639/161532416-8ac4fa09-6a97-4ad9-90da-898dbd486aaf.png)
### Suggested Vulnerability Patch Versions
**opencv-python** has upgraded these vulnerable C libraries to patch versions in release ***4.5.4.64***. 

Python build tools cannot report vulnerable C libraries, which may induce potential security issues to many downstream Python projects.
As a popular python package (*django-social-layer* has **1,560** downloads per month), could you please upgrade this vulnerable dependency

Thanks for your help~
Best regards,
MikeWazowski

**Comment by gsteixeira** [comment]
Hey Mike, thank you for reporting this!
I am looking into it.

**Comment by MikeWazoWski123** [comment]
Hi, @gsteixeira , thank you very much for your support.

**Comment by gsteixeira** [comment]
a new release of DSL is now available.
Thanks for your help.
